### ISSUE TITLE
Attribute "strokeColor" has already been defined and "StrokeWidth"

### ISSUE THREAD

**Issue by n1rocket** [melihaksoy/HoldToLoadLayout#1]
Hello college, 

I have a problem with this attributes, 
`
Error:(289) Attribute "strokeColor" has already been defined
Error:(289) Attribute "strokeWidth" has already been defined
`
Because this params are same that the third party library "CirclePageIndicator".

I like your pretty library and i would like that i can use it. (Can you change the name writing a prefix?)

Thank you 
n1rocket

**Comment by melihaksoy** [comment]
Hello n1rocket,

Thanks for your kind compliment ! I added "hold_" prefix to attributes, I believe this will prevent conflicts that troubles you and anyone using libraries with similar-named attributes.

I also updated the README. Changed version is 1.0.2.

Have a nice day !

**Comment by n1rocket** [comment]
Perfect! Thank you so much
Awesome 💯 
Have a nice day you too!

**Comment by melihaksoy** [comment]
e4ffe038c0ca4d7dfa04fb62af41592aa4798b1a

**Comment by melihaksoy** [comment]
#e4ffe038c0ca4d7dfa04fb62af41592aa4798b1a
