### ISSUE TITLE
Can't stop before given time

### ISSUE THREAD

**Issue by sulaimankhan7** [melihaksoy/HoldToLoadLayout#4]
Hi. I want to do this animation work for at max 30 second. But it can be stopped anytime among 1-30 seconds. How can i stopped that . I have also tried to stop by modifying your class:

    public void myStopper(){
        stopForwardProgressAnimator();
        stopReverseProgressAnimator();
        stopReverseColorAnimator();
        stopForwardColorAnimator();

    }
But still not working

**Comment by melihaksoy** [comment]
Hello,

I'll add a method that will allow you to hold progress still after you stop holding down.

**Comment by sulaimankhan7** [comment]
My problem is solved. I have changed that HoldToLoadLayout according to my need
